### PR TITLE
Adding SendGrid Integration

### PR DESCRIPTION
**Pull request by joefearnley**
Adding SendGrid integration per issue #1.  See the [SendGrid Installation Guide](https://github.com/sendgrid/sendgrid-php#installation) in order to set the API key and if you want to set default TO and FROM information.

### CODE REVIEW

**Comment by peter279k** [comment]
Hi @joefearnley, thank you for your PR.
However, this project is also under the code refactoring.
And the sensitive API keys are exposed that is not make sense....
I plan to let the sensitive API keys assign the encrypted environment variables in ```.travis.yml``` 

What do you think? Thanks.

**Comment by joefearnley** [comment]
Hi @peter279k. I understand. I realize now the test I created is not going to pass unless API credentials are provided. I will remove the test for SendGrid integration. 

If you plan to refactor the whole package, feel free to reject this pull request. Also, if you need help refactoring anything just let me know, I can help.

**Comment by peter279k** [comment]
Hi @joefearnley , please refer this [issue](https://github.com/peter279k/serviceBundle/issues/4).

Please feel free to send the PR. Thanks!

**Comment by joefearnley** [comment]
@peter279k Great! I will probably take a stab at it. Thanks!

**Pull request closed without merging**
